[www]
user = www-data
group = www-data
listen = /var/run/php-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 50
pm.start_servers = 8
pm.min_spare_servers = 4
pm.max_spare_servers = 16
pm.max_requests = 500

slowlog = /dev/stderr
request_slowlog_timeout = 5s

catch_workers_output = yes
decorate_workers_output = no

php_admin_value[error_log] = /dev/stderr
php_admin_flag[log_errors] = on

clear_env = no
