<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Partitioned tables need the partition key in the primary key.
        // Schema::create can't express that, so we use raw DDL.
        DB::statement('
            CREATE TABLE events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                event_type VARCHAR(50) NOT NULL,
                user_id UUID,
                session_id VARCHAR(64),
                locale VARCHAR(10),
                country VARCHAR(2),
                device_type VARCHAR(20),
                browser VARCHAR(50),
                is_bot BOOLEAN NOT NULL DEFAULT false,
                target_url TEXT,
                referrer_url TEXT,
                metadata JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
        ');

        DB::statement(
            'CREATE INDEX idx_events_locale_created ON events (locale, created_at)'
        );
        DB::statement(
            'CREATE INDEX idx_events_type_created ON events (event_type, created_at)'
        );
        DB::statement(
            'CREATE INDEX idx_events_user_created ON events (user_id, created_at)'
        );

        // Create monthly partitions for the next 12 months
        $start = new DateTimeImmutable('first day of this month');
        for ($i = 0; $i < 12; $i++) {
            $monthStart = $start->modify("+{$i} months")->format('Y-m-d');
            $monthEnd = $start->modify('+'.($i + 1).' months')->format('Y-m-d');
            $suffix = $start->modify("+{$i} months")->format('Y_m');

            DB::statement("
                CREATE TABLE events_{$suffix} PARTITION OF events
                FOR VALUES FROM ('{$monthStart}') TO ('{$monthEnd}')
            ");
        }

        // Materialized view for hourly aggregates (excludes bot traffic)
        DB::statement("
            CREATE MATERIALIZED VIEW event_aggregates_hourly AS
            SELECT
                date_trunc('hour', created_at) AS hour,
                event_type,
                locale,
                country,
                device_type,
                COUNT(*) AS event_count,
                COUNT(DISTINCT user_id) AS unique_users,
                COUNT(DISTINCT session_id) AS unique_sessions
            FROM events
            WHERE is_bot = false
            GROUP BY 1, 2, 3, 4, 5
        ");

        DB::statement('
            CREATE UNIQUE INDEX idx_event_agg_hourly
            ON event_aggregates_hourly (hour, event_type, locale, country, device_type)
        ');
    }

    public function down(): void
    {
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS event_aggregates_hourly');
        Schema::dropIfExists('events');
    }
};
