apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoflow-ingress
  namespace: geoflow
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "60"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - geo119.com
        - "*.geo119.com"
      secretName: geo119-tls
  rules:
    - host: geo119.com
      http:
        paths:
          - path: /wp
            pathType: Prefix
            backend:
              service:
                name: geoflow-wordpress
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geoflow-laravel
                port:
                  number: 8080
