apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: geoflow-secrets
  namespace: geoflow
spec:
  encryptedData:
    APP_KEY: ""                 # Fill via kubeseal
    DB_PASSWORD: ""              # Fill via kubeseal
    REDIS_PASSWORD: ""           # Fill via kubeseal
    DEEPSEEK_API_KEY: ""         # Fill via kubeseal
    PAGERDUTY_ROUTING_KEY: ""    # Fill via kubeseal
    STRIPE_SECRET: ""            # Fill via kubeseal
    STRIPE_WEBHOOK_SECRET: ""    # Fill via kubeseal
    PAYPAL_SECRET: ""            # Fill via kubeseal
    MOMO_SECRET: ""              # Fill via kubeseal
    VNPAY_SECRET: ""             # Fill via kubeseal
  template:
    metadata:
      name: geoflow-secrets
      namespace: geoflow
    type: Opaque
